default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 5
  timeout: 5000
  username: <%= ENV['USER'] %>

development:
  <<: *default
  database: word-count/development

test:
  <<: *default
  database: word-count/test

production:
  <<: *default
  database: word-count/production
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
