default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: <%= ENV['USER'] %>

development:
  <<: *default
  database: rails-word-count/development

test:
  <<: *default
  database: rails-word-count/test

production:
  <<: *default
  database: rails-word-count/production
