# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e77544e1752cc8985d0ad56b1d4d9963644dec88ec37633cccba78c93a8414f3bfb13e3b60f558a206bd020970deeb47937b5a8f07046b4b6aeb8c05650ef71

test:
  secret_key_base: 52f49fa7d7d67e2ba1723b6ebdfdc7177dab07ee6ff9760fc5cd54fcc8139088feb6c5e6bda96b213bbb0d464decc58c749b2c8f289d562cbd06339be8235bee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
